-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 21:46:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema unimonito
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema unimonito
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unimonito` DEFAULT CHARACTER SET utf8 ;
USE `unimonito` ;

-- -----------------------------------------------------
-- Table `unimonito`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimonito`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `cedulaCliente` VARCHAR(45) NULL,
  `nombreCliente` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimonito`.`vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimonito`.`vehiculo` (
  `idVehiculo` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(45) NULL,
  `fechaCompra` DATE NULL,
  `idReparacion` VARCHAR(45) NULL,
  `tipoVehiculo` INT NULL,
  PRIMARY KEY (`idVehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimonito`.`cliente_has_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimonito`.`cliente_has_vehiculo` (
  `cliente_idCliente` INT NOT NULL,
  `vehiculo_idVehiculo` INT NOT NULL,
  `numPlaca` VARCHAR(45) NULL,
  PRIMARY KEY (`cliente_idCliente`, `vehiculo_idVehiculo`),
  INDEX `fk_cliente_has_vehiculo_vehiculo1_idx` (`vehiculo_idVehiculo` ASC),
  INDEX `fk_cliente_has_vehiculo_cliente_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_cliente_has_vehiculo_cliente`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `unimonito`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_vehiculo_vehiculo1`
    FOREIGN KEY (`vehiculo_idVehiculo`)
    REFERENCES `unimonito`.`vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimonito`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimonito`.`ciudad` (
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `nombreCiudad` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`idCiudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimonito`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimonito`.`localidad` (
  `idLocalidad` INT NOT NULL AUTO_INCREMENT,
  `nombreLocalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimonito`.`franquicia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimonito`.`franquicia` (
  `idFranquicia` INT NOT NULL AUTO_INCREMENT,
  `nombreFranquicia` VARCHAR(45) NULL,
  `director` VARCHAR(45) NULL,
  `ciudad_idCiudad` INT NOT NULL,
  `localidad_idLocalidad` INT NOT NULL,
  PRIMARY KEY (`idFranquicia`, `ciudad_idCiudad`, `localidad_idLocalidad`),
  INDEX `fk_franquicia_ciudad1_idx` (`ciudad_idCiudad` ASC),
  INDEX `fk_franquicia_localidad1_idx` (`localidad_idLocalidad` ASC),
  CONSTRAINT `fk_franquicia_ciudad1`
    FOREIGN KEY (`ciudad_idCiudad`)
    REFERENCES `unimonito`.`ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_franquicia_localidad1`
    FOREIGN KEY (`localidad_idLocalidad`)
    REFERENCES `unimonito`.`localidad` (`idLocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimonito`.`franquicia_has_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimonito`.`franquicia_has_vehiculo` (
  `franquicia_idFranquicia` INT NOT NULL,
  `vehiculo_idVehiculo` INT NOT NULL,
  PRIMARY KEY (`franquicia_idFranquicia`, `vehiculo_idVehiculo`),
  INDEX `fk_franquicia_has_vehiculo_vehiculo1_idx` (`vehiculo_idVehiculo` ASC),
  INDEX `fk_franquicia_has_vehiculo_franquicia1_idx` (`franquicia_idFranquicia` ASC),
  CONSTRAINT `fk_franquicia_has_vehiculo_franquicia1`
    FOREIGN KEY (`franquicia_idFranquicia`)
    REFERENCES `unimonito`.`franquicia` (`idFranquicia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_franquicia_has_vehiculo_vehiculo1`
    FOREIGN KEY (`vehiculo_idVehiculo`)
    REFERENCES `unimonito`.`vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimonito`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimonito`.`empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `cedulaEmpleado` VARCHAR(45) NULL,
  `nombreEmpleado` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `fechaContrato` DATE NULL,
  `salario` INT NULL,
  `franquicia_idFranquicia` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`, `franquicia_idFranquicia`),
  INDEX `fk_empleado_franquicia1_idx` (`franquicia_idFranquicia` ASC),
  CONSTRAINT `fk_empleado_franquicia1`
    FOREIGN KEY (`franquicia_idFranquicia`)
    REFERENCES `unimonito`.`franquicia` (`idFranquicia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimonito`.`reparacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimonito`.`reparacion` (
  `idReparacion` INT NOT NULL AUTO_INCREMENT,
  `fechaReparacion` DATE NULL,
  `idTipoReparacion` INT NULL,
  `precioReparacion` INT NULL,
  `observacion` VARCHAR(45) NULL,
  `vehiculo_idVehiculo` INT NOT NULL,
  PRIMARY KEY (`idReparacion`, `vehiculo_idVehiculo`),
  INDEX `fk_reparacion_vehiculo1_idx` (`vehiculo_idVehiculo` ASC),
  CONSTRAINT `fk_reparacion_vehiculo1`
    FOREIGN KEY (`vehiculo_idVehiculo`)
    REFERENCES `unimonito`.`vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimonito`.`tipoReparacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimonito`.`tipoReparacion` (
  `idTipoReparacion` INT NOT NULL AUTO_INCREMENT,
  `tipoReparacion` VARCHAR(45) NULL,
  `reparacion_idReparacion` INT NOT NULL,
  `reparacion_vehiculo_idVehiculo` INT NOT NULL,
  PRIMARY KEY (`idTipoReparacion`, `reparacion_idReparacion`, `reparacion_vehiculo_idVehiculo`),
  INDEX `fk_tipoReparacion_reparacion1_idx` (`reparacion_idReparacion` ASC, `reparacion_vehiculo_idVehiculo` ASC),
  CONSTRAINT `fk_tipoReparacion_reparacion1`
    FOREIGN KEY (`reparacion_idReparacion` , `reparacion_vehiculo_idVehiculo`)
    REFERENCES `unimonito`.`reparacion` (`idReparacion` , `vehiculo_idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimonito`.`vehiculoUtilitario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimonito`.`vehiculoUtilitario` (
  `num_puertas` INT NULL,
  `vehiculo_idVehiculo` INT NOT NULL,
  PRIMARY KEY (`vehiculo_idVehiculo`),
  CONSTRAINT `fk_vehiculoUtilitario_vehiculo1`
    FOREIGN KEY (`vehiculo_idVehiculo`)
    REFERENCES `unimonito`.`vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimonito`.`vehiculoTodoTerreno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimonito`.`vehiculoTodoTerreno` (
  `numDefensas` INT NULL,
  `vehiculo_idVehiculo` INT NOT NULL,
  PRIMARY KEY (`vehiculo_idVehiculo`),
  CONSTRAINT `fk_vehiculoTodoTerreno_vehiculo1`
    FOREIGN KEY (`vehiculo_idVehiculo`)
    REFERENCES `unimonito`.`vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimonito`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimonito`.`usuario` (
  `empleado_idEmpleado` INT NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  `username` INT NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `tipoUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`empleado_idEmpleado`, `cliente_idCliente`),
  INDEX `fk_usuario_empleado1_idx` (`empleado_idEmpleado` ASC),
  CONSTRAINT `fk_usuario_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `unimonito`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_empleado1`
    FOREIGN KEY (`empleado_idEmpleado`)
    REFERENCES `unimonito`.`empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
